"""empty message

Revision ID: 663f7d223b5f
Revises: 7f920bc95796
Create Date: 2019-06-20 19:21:51.454416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663f7d223b5f'
down_revision = '7f920bc95796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages_guest_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_content', sa.String(length=450), nullable=True),
    sa.Column('guest_user', sa.String(length=64), nullable=True),
    sa.Column('guest_time', sa.DateTime(), nullable=True),
    sa.Column('page_id', sa.String(length=13), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.page_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_guest_book_id'), 'pages_guest_book', ['id'], unique=False)
    op.create_index(op.f('ix_pages_guest_book_page_id'), 'pages_guest_book', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pages_guest_book_page_id'), table_name='pages_guest_book')
    op.drop_index(op.f('ix_pages_guest_book_id'), table_name='pages_guest_book')
    op.drop_table('pages_guest_book')
    # ### end Alembic commands ###
