"""empty message

Revision ID: beefec957994
Revises: 663f7d223b5f
Create Date: 2019-06-25 17:14:29.955295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beefec957994'
down_revision = '663f7d223b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('content_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'content_type')
    # ### end Alembic commands ###
